name: Matrix with Needs and Outputs
 
on:
  workflow_dispatch
 
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.set-status.outputs.result }}
    steps:
      - name: Build Project
        run: echo "Building project..."
 
      - name: Set build result
        id: set-status
        run: echo "result=success" >> $GITHUB_OUTPUT
 
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
 
      - name: Run Tests
        run: echo "Running tests on Node ${{ matrix.node-version }}"
 
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Deploy
        run: echo "✅ Deploying App - All tests passed!"
