name: PR Merge Context Logger
 
on:
  pull_request:
    types:
      - closed
 
jobs:
  log_context_on_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Log GitHub Context
        run: |
          echo 'PR Merged by: ${{ github.actor }}'
          echo 'Repository: ${{ github.repository }}'
          echo 'Branch: ${{ github.ref }}'
          echo 'Event: ${{ github.event_name }}'
